name: UI Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run UI Tests with Allure
        run: mvn clean test -Dallure.results.directory=target/allure-results

      - name: Checkout gh-pages branch for history
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy history from gh-pages
        run: |
          mkdir -p target/allure-results/history
          cp -r gh-pages/history/* target/allure-results/history/ || echo "No previous history"

      - name: Trim history to last 10 entries
        run: |
          cd target/allure-results/history
          ls -t | tail -n +11 | xargs rm -f || echo "Nothing to trim"

      - name: Download and Generate Allure Report
        run: |
          curl -o allure-2.27.0.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          allure-2.27.0/bin/allure generate target/allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
