name: UI Tests

on:
  workflow_dispatch:

jobs:
  allure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run UI Tests
        run: mvn clean test -Dallure.results.directory=target/allure-results

      - name: Publish Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: target/allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
          github_token: ${{ secrets.GITHUB_TOKEN }}
